### ISSUE TITLE
Allow data tab to use external data

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/editor4#32]
I am currently creating a docker image that can expose any database data either via oData or Json.

Example for Json:

```
http://localhost:8080/HanaAppContainer/protected/rest/query?$select=SELECT%20OBJECT_TYPE,%20count(*)%20as%20COUNT%20FROM%20objects%20GROUP%20BY%20OBJECT_TYPE
```

returns

```
[
 {"OBJECT_TYPE":"TABLE","COUNT":18},
 {"OBJECT_TYPE":"VIEW","COUNT":614},
 {"OBJECT_TYPE":"INDEX","COUNT":3},
 ...
]
```

If the data tab would support URLs, the user could view the data and pick the columns from the Json element names.

With oData one more level would be possible, creating the URL! The user points to the service endpoint, this exposes the metadata. You read the metadata and allow the user to build the query URL interactively.

**Comment by ailon** [comment]
Hi,

Thank you for reaching out!

amCharts has built-in way of loading external data so we felt that it would be confusing to duplicated it in the Editor making it unclear what would happen next (would it be a static snapshot of that data in the editor, or a live data set and what happens if you try to edit it).

You can read more about loading data here:
https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/

We may revisit this in the future though.
