### ISSUE TITLE
Import from Code is stripping properties

### ISSUE THREAD

**Issue by ChazUK** [amcharts/editor4#60]
I've been trying to import a chart from code into the editor and scratching my head why the properties listed in the docs aren't working properly. After diff'ing the original json config against the one that is displayed in the code tab on the editor I noticed that properties are being removed. `heatRules` is the main one which is causing issues.

Original https://gist.github.com/ChazUK/a6406eb9e9012b39d87d54756a35b289 -> https://codepen.io/ChazUK/pen/NWjgEeX
<img width="1504" alt="Screenshot 2021-07-19 at 17 43 47" src="https://user-images.githubusercontent.com/768108/126196410-f2787f10-9ebf-4dec-b6f6-bdd312828520.png">

Exported https://gist.github.com/ChazUK/fb1d4251af9e35ade77166c49328cf8e -> https://codepen.io/ChazUK/pen/QWvgzBo
<img width="1511" alt="Screenshot 2021-07-19 at 17 41 44" src="https://user-images.githubusercontent.com/768108/126196433-f5f484f0-1b17-4757-98a2-5a852744cb0d.png">

Is there a step in the import that expands / removes certain properties?

Also the legend is not being positioned correctly.

**Comment by ailon** [comment]
Hi Charles,

Unfortunately, heatRules are not supported by the Editor due to internal complexities.

While we try to support as many amCharts features as possible in the Editor, the general rule of thumb is that the Editor is mainly targeting scenarios where the charts being edited were created with Editor in the first place.
